import torch
import torch.nn as nn
from torchvision import models
import gc

class Branch1_CNN(nn.Module):
    def __init__(self):
        super().__init__()
        # weights=None because we are loading your custom trained weights later
        self.backbone = models.efficientnet_b5(weights=None) 
        self.features_extractor = self.backbone.features
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.classifier = nn.Linear(2048, 2)

    def forward(self, x):
        fm = self.features_extractor(x)
        pooled = self.pool(fm).flatten(1)
        score = self.classifier(pooled)
        return fm, score

class Branch2_ViT(nn.Module):
    def __init__(self):
        super().__init__()
        self.backbone = models.swin_t(weights=None)
        self.backbone.head = nn.Linear(self.backbone.head.in_features, 2)

    def forward(self, x):
        return self.backbone(x)

class Branch3_Hybrid(nn.Module):
    def __init__(self):
        super().__init__()
        encoder_layer = nn.TransformerEncoderLayer(d_model=2048, nhead=8, batch_first=True)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=2)
        self.classifier = nn.Linear(2048, 2)

    def forward(self, cnn_feature_map):
        B, C, H, W = cnn_feature_map.shape
        x = cnn_feature_map.view(B, C, H * W).permute(0, 2, 1)
        x = self.transformer(x)
        x = x.mean(dim=1)
        return self.classifier(x)

class ArtForgeryEngine(nn.Module):
    def __init__(self):
        super().__init__()
        self.cnn = Branch1_CNN()
        self.vit = Branch2_ViT()
        self.hybrid = Branch3_Hybrid()

    def forward(self, rgb, gray, edge):
        # Adapt 1-channel edge map to 3-channel for the EfficientNet
        edge_3ch = edge.repeat(1, 3, 1, 1)

        # Route the specific tensors to their specialized branches
        cnn_features, cnn_score = self.cnn(edge_3ch)
        vit_score = self.vit(rgb)
        hybrid_score = self.hybrid(cnn_features)
        
        return cnn_score, vit_score, hybrid_score

def load_engine(model_path="models/ArtForgeryEngine_V2_Advanced.pth"):
    print("Loading AI Engine into CPU Memory...")
    engine = ArtForgeryEngine()
    
    # map_location='cpu' is critical here! It forces the GPU-trained weights to work on your laptop's CPU
    engine.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))

    engine.eval() # Locks the brain into inference mode
    return engine

def analyze_painting(engine, image_tensors):
    # Unpack the batches generated by preprocessing.py
    rgb_batch, gray_batch, edge_batch = image_tensors

    with torch.no_grad():
        # Pass the ENTIRE batch of multi-scale patches through the engine at once
        cnn_out, vit_out, hybrid_out = engine(rgb_batch, gray_batch, edge_batch)
        
        # Apply Softmax to convert raw logits into percentages (0.0 to 1.0)
        # We grab index [:, 1] which represents the "Forgery" class probability for every patch
        cnn_probs = torch.softmax(cnn_out, dim=1)[:, 1]
        vit_probs = torch.softmax(vit_out, dim=1)[:, 1]
        hybrid_probs = torch.softmax(hybrid_out, dim=1)[:, 1]

        # Mathematically average the forgery probability across all patches
        cnn_prob_avg = cnn_probs.mean().item() * 100
        vit_prob_avg = vit_probs.mean().item() * 100
        hybrid_prob_avg = hybrid_probs.mean().item() * 100

        # differential evlutn weights
       
        w_cnn = 0.029
        w_vit = 0.876
        w_hybrid = 0.095
        
        # Calculate the final ensemble score
        final_score = (cnn_prob_avg * w_cnn) + (vit_prob_avg * w_vit) + (hybrid_prob_avg * w_hybrid)
        
        # Aggressive memory cleanup so the Flask server doesn't crash on the next upload
        del cnn_out, vit_out, hybrid_out, rgb_batch, gray_batch, edge_batch
        gc.collect()

        return {
            "final_score": round(final_score, 2),
            "cnn_confidence": round(cnn_prob_avg, 2),
            "vit_confidence": round(vit_prob_avg, 2),
            "hybrid_confidence": round(hybrid_prob_avg, 2)
        }